apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-jdbc-enabled
data:
  jdbc.properties: |
    initdb=false
    import=false
    enabled=true
    username={{ .Values.jdbc.username }}
    password={{ .Values.jdbc.password }}
    jdbcUrl={{ .Values.jdbc.url }}
    pool.poolPreparedStatements=false
    pool.testWhileIdle=false
    pool.timeBetweenEvictionRunsMillis=-1L
    pool.validationQuery=SELECT now()
    pool.minIdle=4
    ignoreDirs=.git,data,jdbcstore,jdbcconfig,temp,tmp,logs,wps_data,cluster,gwc-layers
    pool.maxOpenPreparedStatements=50
    driverClassName=org.postgresql.Driver
    pool.maxActive=10
    initScript=jdbcconfig/scripts/initdb.postgres.sql
    debugMode=false
    pool.testOnBorrow=true