prometheus:
  url: http://kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090

metricsRelistInterval: 30s
extraArguments:
  - --metrics-max-age=2m

rules:
  default: false
  custom:
    - seriesQuery: 'requests_total_seconds_count{namespace="geoserver",job="geoserver",pod=~"geoserver-[0-9]+",cluster=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^requests_total_seconds_count$
        as: geoserver_requests_total_per_second
      metricsQuery: >-
        sum by (<<.GroupBy>>) (
          rate(<<.Series>>{<<.LabelMatchers>>,namespace="geoserver",job="geoserver",pod=~"geoserver-[0-9]+",cluster=""}[2m])
          and on (cluster,namespace,pod,job,instance)
          (up{namespace="geoserver",job="geoserver",pod=~"geoserver-[0-9]+",cluster=""} == 1)
        )
    - seriesQuery: 'java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^java_lang_Memory_HeapMemoryUsage_used$
        as: geoserver_heap_used_percent
      metricsQuery: >-
        (max by (<<.GroupBy>>) ((
              (100 * avg_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) / java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})
              and (java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>} > 0)
              and (min_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 0)
              and (max_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) <= java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})
              and (count_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 3)
              and (count_over_time(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 3)
              and (changes(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) == 0)
              and ((time() - timestamp(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45)
              and ((time() - timestamp(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45)
              and on (cluster,namespace,pod,job,instance) ((up{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>} == 1) and ((time() - timestamp(up{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45))
            ))) and on (<<.GroupBy>>) (count by (<<.GroupBy>>) ((
              (100 * avg_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) / java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})
              and (java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>} > 0)
              and (min_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 0)
              and (max_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) <= java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})
              and (count_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 3)
              and (count_over_time(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 3)
              and (changes(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) == 0)
              and ((time() - timestamp(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45)
              and ((time() - timestamp(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45)
              and on (cluster,namespace,pod,job,instance) ((up{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>} == 1) and ((time() - timestamp(up{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45))
            )) == 1)
    - seriesQuery: 'java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: ^java_lang_Memory_HeapMemoryUsage_used$
        as: geoserver_heap_pressure_percent
      # Activation level: 50%. If changed, also set HPA target = high - activation.
      metricsQuery: >-
        clamp_min(((max by (<<.GroupBy>>) ((
              (100 * avg_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) / java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})
              and (java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>} > 0)
              and (min_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 0)
              and (max_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) <= java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})
              and (count_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 3)
              and (count_over_time(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 3)
              and (changes(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) == 0)
              and ((time() - timestamp(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45)
              and ((time() - timestamp(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45)
              and on (cluster,namespace,pod,job,instance) ((up{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>} == 1) and ((time() - timestamp(up{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45))
            ))) and on (<<.GroupBy>>) (count by (<<.GroupBy>>) ((
              (100 * avg_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) / java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})
              and (java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>} > 0)
              and (min_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 0)
              and (max_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) <= java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})
              and (count_over_time(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 3)
              and (count_over_time(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) >= 3)
              and (changes(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>}[120s]) == 0)
              and ((time() - timestamp(java_lang_Memory_HeapMemoryUsage_used{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45)
              and ((time() - timestamp(java_lang_Memory_HeapMemoryUsage_max{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45)
              and on (cluster,namespace,pod,job,instance) ((up{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>} == 1) and ((time() - timestamp(up{namespace="geoserver",job="geoserver-jmx",pod=~"geoserver-[0-9]+",cluster="",<<.LabelMatchers>>})) < 45))
            )) == 1)) - 50, 0)
  external: []

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
logLevel: 4
