apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mapstore.fullname" . }}-ovr
data:
  geostore_driverClassName: {{ .Values.secrets.geostoreDataSource.driverClassName | b64enc | quote }}
  geostore_url: {{ .Values.secrets.geostoreDataSource.url | b64enc | quote }}
  geostore_username: {{ .Values.secrets.geostoreDataSource.username | b64enc | quote }}
  geostore_password: {{ .Values.secrets.geostoreDataSource.password | b64enc | quote }}
  geostore_databasePlatform: {{ .Values.secrets.geostoreVendorAdapter.databasePlatform | b64enc | quote }}
  geostore_hbm2ddl_auto: {{ .Values.secrets.geostoreEntityManagerFactory.jpaPropertyMap.hbm2ddl_auto | b64enc | quote }}
  geostore_default_schema: {{ .Values.secrets.geostoreEntityManagerFactory.jpaPropertyMap.default_schema | b64enc | quote }}
  geostore_generateDdl: {{ .Values.secrets.geostoreVendorAdapter.generateDdl | b64enc | quote }}
  geostore_showSql: {{ .Values.secrets.geostoreVendorAdapter.showSql | b64enc | quote }}
type: {{ .Values.secrets.kind }}
