{{- define "mapstore.ovr-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mapstore.fullname" . }}-ovr
data:
  geostore-datasource-ovr.properties: |-
    {{ .Files.Get "geostore-datasource-ovr.properties" | b64enc }}
{{- end -}}
{{- include "mapstore.ovr-secret" . -}}
