apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mapstore.fullname" . }}-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistence.requests.storage | quote }}
  volumeMode: {{ .Values.persistence.volumeMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- if .Values.persistence.hostPath }}
  hostPath:
    path: {{ .Values.persistence.hostPath.path  }}
  {{- end }}

