apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mapstore.fullname" . }}
  labels:
    {{- include "mapstore.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mapstore.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mapstore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mapstore.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: {{ .Values.env.JAVA_OPTS }}
            - name: GEOSTORE_OVR_OPT
              value: "-Dgeostore-ovr=file:///config/geostore-datasource-ovr.properties"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: datadir
              mountPath: /var/mapstore/datadir
            - name: ovr-properties
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ include "mapstore.fullname" . }}
        - name: ovr-properties
          secret:
            secretName: {{ include "mapstore.fullname" . }}-ovr
