apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mapstore.fullname" . }}
  labels:
    {{- include "mapstore.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mapstore.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mapstore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mapstore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: {{ .Values.env.JAVA_OPTS }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: datadir
              mountPath: /datadir
            - name: ovr-properties
              mountPath: "/config/geostore-datasource-ovr.properties"
              subPath: geostore-datasource-ovr.properties
              readOnly: true
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ include "mapstore.fullname" . }}
        - name: ovr-properties
          secret:
            secretName: {{ include "mapstore.fullname" . }}-ovr
