apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mapstore.fullname" . }}
  labels:
    {{- include "mapstore.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mapstore.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mapstore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mapstore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: Always
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /mapstore/
              port: http
            failureThreshold: 136
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /mapstore/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /mapstore/
              port: http
            successThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: datadir
              mountPath: /datadir
            - name: ovr-properties
              mountPath: "/config/geostore-datasource-ovr.properties"
              subPath: geostore-datasource-ovr.properties
              readOnly: true
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ include "mapstore.fullname" . }}
        - name: ovr-properties
          secret:
            secretName: {{ include "mapstore.fullname" . }}-ovr
