apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mapstore.fullname" . }}
  labels:
    {{- include "mapstore.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mapstore.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mapstore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mapstore.selectorLabels" . | nindent 8 }}
    spec:
      hostAliases:
      # Hardcoded here. Need to think of a better solution.
      - ip: "10.136.19.68"
        hostnames:
        - "geoserver-dev.corp.fisc.brussels"
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['sh', '-c', 'keytool -import -trustcacerts -alias geoserver_ca_cert -file /usr/local/tomcat/conf/certs/custom-root-ca.cer -cacerts -storepass changeit -noprompt && keytool -import -trustcacerts -alias geoserver_issuing -file /usr/local/tomcat/conf/certs/custom-intermediate-ca.cer -cacerts -storepass changeit -noprompt && catalina.sh run']
          env:
            - name: JAVA_OPTS
              value: {{ .Values.env.JAVA_OPTS }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: datadir
              mountPath: /datadir
            - name: ovr-properties
              mountPath: "/config/geostore-datasource-ovr.properties"
              subPath: geostore-datasource-ovr.properties
              readOnly: true
            - name: custom-ca-cert
              mountPath: "/usr/local/tomcat/conf/certs/custom-root-ca.cer"
              subPath: custom-root-ca.cer
              readOnly: true
            - name: custom-ca-cert
              mountPath: "/usr/local/tomcat/conf/certs/custom-intermediate-ca.cer"
              subPath: custom-intermediate-ca.cer
              readOnly: true
      volumes:
        - name: custom-ca-cert
          secret:
            secretName: {{ include "mapstore.fullname" . }}-custom-ca-cert
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ include "mapstore.fullname" . }}
        - name: ovr-properties
          secret:
            secretName: {{ include "mapstore.fullname" . }}-ovr
