# This values.yaml has intentional syntax errors for testing lint failures

replicaCount: 1

image:
  repository: geosolutionsit/geoserver
  tag: "2.27.0"
  # Invalid YAML syntax - missing closing quote
  pullPolicy: "IfNotPresent

# Invalid indentation will cause YAML parsing error
service:
type: ClusterIP
  port: 80

# Invalid key with special characters
invalid-key-with-@#$: "this will fail"

# Incorrect array syntax
tags:
  - valid-tag
  - 
    invalid: nested
  - another-tag

# Missing closing bracket
resources: {
  limits:
    cpu: "100m"
    memory: "128Mi"
}
