{{- if and .Values.monitoring.serviceMonitor.enabled .Values.monitoring.serviceMonitor.basicAuth.enabled .Values.monitoring.serviceMonitor.basicAuth.createSecret .Values.monitoring.serviceMonitor.basicAuth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.monitoring.serviceMonitor.basicAuth.existingSecret }}
  namespace: {{ default .Release.Namespace .Values.monitoring.serviceMonitor.namespace }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.monitoring.serviceMonitor.basicAuth.usernameKey }}: {{ .Values.monitoring.serviceMonitor.basicAuth.username | b64enc | quote }}
  {{ .Values.monitoring.serviceMonitor.basicAuth.passwordKey }}: {{ .Values.secrets.admin_password | b64enc | quote }}
{{- end }}
