{{- if and .Values.persistence.datadir (not .Values.persistence.datadir.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-datadir
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.datadir.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.datadir.size | quote }}
  {{- if .Values.persistence.datadir.storageClass }}
  storageClassName: {{ .Values.persistence.datadir.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.datadirbackoffice (not .Values.persistence.datadirbackoffice.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-datadirbackoffice
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.datadirbackoffice.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.datadirbackoffice.size | quote }}
  {{- if .Values.persistence.datadirbackoffice.storageClass }}
  storageClassName: {{ .Values.persistence.datadirbackoffice.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.data (not .Values.persistence.data.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-data
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.memdumps (not .Values.persistence.memdumps.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-memdumps
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.memdumps.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.memdumps.size | quote }}
  {{- if .Values.persistence.memdumps.storageClass }}
  storageClassName: {{ .Values.persistence.memdumps.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.postgis.enabled (not .Values.persistence.postgis.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-postgis
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.postgis.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.postgis.size | quote }}
  {{- if .Values.persistence.postgis.storageClass }}
  storageClassName: {{ .Values.persistence.postgis.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.audits (not .Values.persistence.audits.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-audits
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.audits.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.audits.size | quote }}
  {{- if .Values.persistence.audits.storageClass }}
  storageClassName: {{ .Values.persistence.audits.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.logs (not .Values.persistence.logs.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-logs
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
  {{- if .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.tomcatlogs (not .Values.persistence.tomcatlogs.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-tomcatlogs
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.tomcatlogs.size | quote }}
  {{- if .Values.persistence.tomcatlogs.storageClass }}
  storageClassName: {{ .Values.persistence.tomcatlogs.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.wps (not .Values.persistence.wps.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-wps
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.wps.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.wps.size | quote }}
  {{- if .Values.persistence.wps.storageClass }}
  storageClassName: {{ .Values.persistence.wps.storageClass }}
  {{- end }}
{{- end }}
