{{- define "geoserver.secrets" -}}
{{- if not (and .Values.secrets.postgis_external_secret .Values.secrets.admin_external_secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
data:
  {{- if not .Values.secrets.postgis_external_secret }}
  POSTGIS_PASSWORD: {{ .Values.secrets.postgis_password | b64enc | quote}}
  {{- end }}
  {{- if not .Values.secrets.admin_external_secret }}
  ADMIN_PASSWORD: {{ .Values.secrets.admin_password | b64enc | quote}}
  {{- end }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoserver.fullname" . }}-context
data:
  context.xml: {{ include "geoserver.context.xml" . | b64enc | quote }}
{{- end -}}
{{- include "geoserver.secrets" . -}}
