apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
data:
  POSTGIS_PASSWORD: {{ .Values.secrets.postgis_password | b64enc | quote}}
  ADMIN_PASSWORD: {{ .Values.secrets.admin_password | b64enc | quote}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoserver.fullname" . }}-context
data:
  context.xml: |-
              {{ .Files.Get "context.xml" | b64enc }}
