apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}

---

{{- if .Values.backoffice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}-backoffice
  labels:
    {{- include "geoserver.labelsBackoffice" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "geoserver.selectorLabelsBackoffice" . | nindent 4 }}
{{- end }}
