apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "geoserver.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "geoserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geoserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          invalidResourceField:
            cpu: "100m"
            memory: "128Mi"
          volumeMounts:
            - name: invalid-volume
              mountPath: /invalid
              readOnlyRoot: true
              invalidField: "value"
          env:
            - name: TEST_VAR
              wrongFrom:
                secretKeyRef:
                  name: test-secret
                  key: test-key
      volumes:
        - name: invalid-volume
          invalidVolumeType:
            path: /tmp
      invalidPodField: "invalid"
