nameOverride: ""
fullnameOverride: ""

image:
  name: geosolutionsit/mapstore2
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  nodePort: 30000

ingress:
  className: nginx
  host: mapstore.local
  path: /mapstore
  backendServicePort: 8080
  # tlsEnabled instructs the ingress to use a certificate from k8s secret. The secret has to the chart name suffixed by -tls. eg: "mapstore-tls"
  tlsEnabled: false

persistence:
  accessModes: ReadWriteOnce
  requests:
    storage: 5Gi
  storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mapstore-datadir

env:
  JAVA_OPTS: "-Xms512m -Xmx512m -Ddatadir.location=/datadir -Dgeostore-ovr=file:///config/geostore-datasource-ovr.properties"
